id: P005577
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1CZ2043
  title: མི་ཕམ་བློ་གྲོས་རྒྱ་མཚོའི་རྣམ་ཐར་རྒྱ་མཚོའི་བཅུད་བསྡུས་བརྡ་དོན་ངོ་མཚར་སྣང་བ
  author: ''
  volumes:
    7f636b30987d4b7a8419bdf10da7dfc3:
      image_group_id: I1CZ2160
      title: ''
      volume_number: 1
      total_pages: 144
      base_file: v001.txt
