id: IC864A4CC
legacy_id: P005577
ocr_import_info:
  bdrc_scan_id: W1CZ2043
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T06:10:58'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T19:12:47.845171+00:00'
last_modified: 2022-08-31 03:13:05.510479
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1CZ2043
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1CZ2043
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མི་ཕམ་བློ་གྲོས་རྒྱ་མཚོའི་རྣམ་ཐར་རྒྱ་མཚོའི་བཅུད་བསྡུས་བརྡ་དོན་ངོ་མཚར་སྣང་བ།
  author: མི་ཕམ་ཆོས་དཔལ་བཟང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.5308458864447859
  ocr_word_median_confidence_index: 0.4699999988079071
quality: null
bases:
  I1CZ2160:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ2160
      total_pages: 144
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ2160.txt
    statistics:
      ocr_word_median_confidence_index: 0.4699999988079071
      ocr_word_mean_confidence_index: 0.5308458864447859
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
