id: IC864A4CC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T06:12:02+00:00'
last_modified: '2022-06-08T05:02:48.207305+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ2043
  title: མི་ཕམ་བློ་གྲོས་རྒྱ་མཚོའི་རྣམ་ཐར་རྒྱ་མཚོའི་བཅུད་བསྡུས་བརྡ་དོན་ངོ་མཚར་སྣང་བ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '3883':
      image_group_id: I1CZ2160
      title: ''
      total_pages: 144
      order: 1
      base_file: 3883.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
